# Generated by Django 5.2.6 on 2026-04-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angsuran',
            options={'managed': True, 'ordering': ['tanggal_jatuh_tempo'], 'verbose_name_plural': 'Angsuran'},
        ),
        migrations.AlterModelOptions(
            name='pinjaman',
            options={'managed': True, 'verbose_name_plural': 'Pinjaman'},
        ),
        migrations.AlterModelOptions(
            name='riwayatpembayaran',
            options={'managed': True, 'ordering': ['-tanggal_bayar'], 'verbose_name_plural': 'Riwayat Pembayaran'},
        ),
    ]
