# Generated by Django 5.2.6 on 2026-04-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angsuran',
            fields=[
                ('id_angsuran', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=20)),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='Belum', max_length=20)),
                ('tanggal_bayar', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Angsuran',
                'db_table': 'angsuran',
                'ordering': ['tanggal_jatuh_tempo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id_pinjaman', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_kontrak', models.CharField(max_length=50, unique=True)),
                ('total_pinjaman', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sisa_pinjaman', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenor', models.IntegerField()),
                ('bunga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('angsuran_per_bulan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal_cair', models.DateField()),
                ('status', models.CharField(default='Aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pinjaman',
                'db_table': 'pinjaman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiwayatPembayaran',
            fields=[
                ('id_riwayat', models.AutoField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(default='angsuran', max_length=20)),
                ('transaksi', models.CharField(max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metode', models.CharField(max_length=50)),
                ('status', models.CharField(default='Sukses', max_length=20)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Riwayat Pembayaran',
                'db_table': 'riwayat_pembayaran',
                'ordering': ['-tanggal_bayar'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tabel_nasabah',
            fields=[
                ('id_nasabah', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=15000000, max_digits=15)),
                ('tanggal_bergabung', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Nasabah',
                'db_table': 'tabel_nasabah',
                'managed': False,
            },
        ),
    ]
