# Generated by Django 5.2.13 on 2026-04-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_angsuran_options_alter_pinjaman_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id_nasabah', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nasabah',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Angsuran',
        ),
        migrations.DeleteModel(
            name='RiwayatPembayaran',
        ),
        migrations.DeleteModel(
            name='tabel_nasabah',
        ),
        migrations.AlterModelOptions(
            name='pinjaman',
            options={'managed': False},
        ),
    ]
